
import React, { useState, useEffect } from 'react';
import { User, Job, CommissionRecord, Candidate, ActivityLog } from '../types';
import { Calendar, TrendingUp, Users, DollarSign, ChevronDown, ChevronUp, Download, Lock, Filter, Briefcase, User as UserIcon, FileText, List, Clock, CheckCircle, Activity } from 'lucide-react';

interface MonthlyReportsProps {
  jobs: Job[];
  users: User[];
  commissions: CommissionRecord[];
  candidates: Candidate[];
  currentUser: User | null;
  activityLogs?: ActivityLog[]; // New Prop
}

interface MonthlyData {
  id: string; // "YYYY-MM"
  label: string; // "October 2023"
  totalRevenue: number;
  totalPlacements: number;
  activeJobsCount: number;
  topRecruiterId: string;
  topRecruiterName: string;
}

const MonthlyReports: React.FC<MonthlyReportsProps> = ({ jobs, users, commissions, candidates, currentUser, activityLogs = [] }) => {
  const isAdmin = currentUser?.role === 'Admin' || currentUser?.role === 'SuperAdmin';

  const [activeTab, setActiveTab] = useState<'daily' | 'monthly' | 'user_history'>('daily');
  const [selectedUser, setSelectedUser] = useState<string>(isAdmin ? 'all' : (currentUser?.id || 'all'));
  
  // Daily Report State
  const [selectedDate, setSelectedDate] = useState<string>(new Date().toISOString().split('T')[0]);

  // Monthly Drill Down State
  const [selectedYear, setSelectedYear] = useState<number>(new Date().getFullYear());
  const [expandedMonthId, setExpandedMonthId] = useState<string | null>(null);

  useEffect(() => {
      if (!isAdmin) {
          setActiveTab('daily'); // Everyone can see daily logs (filtered to them or general)
          setSelectedUser(currentUser?.id || '');
      }
  }, [isAdmin, currentUser]);

  // --- Daily Report Logic ---
  const getDailyLogs = () => {
      const start = new Date(selectedDate).setHours(0,0,0,0);
      const end = new Date(selectedDate).setHours(23,59,59,999);
      
      return activityLogs.filter(log => {
          const logTime = new Date(log.timestamp).getTime();
          const matchesDate = logTime >= start && logTime <= end;
          const matchesUser = isAdmin ? (selectedUser === 'all' || log.userId === selectedUser) : log.userId === currentUser?.id;
          return matchesDate && matchesUser;
      }).sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()); // Newest first
  };

  const dailyLogs = getDailyLogs();
  
  const dailyStats = {
      actions: dailyLogs.length,
      jobs: dailyLogs.filter(l => l.type === 'Job').length,
      candidates: dailyLogs.filter(l => l.type === 'Candidate').length,
      system: dailyLogs.filter(l => l.type === 'System' || l.type === 'Client').length
  };

  const handleDownloadDailyReport = () => {
      const lines = [
          `DAILY ACTIVITY REPORT - THE HIRING ORG`,
          `Date: ${selectedDate}`,
          `Generated By: ${currentUser?.name}`,
          `Target User: ${selectedUser === 'all' ? 'Entire Team' : users.find(u => u.id === selectedUser)?.name}`,
          `-------------------------------------------`,
          `SUMMARY METRICS`,
          `Total Actions: ${dailyStats.actions}`,
          `Jobs Managed: ${dailyStats.jobs}`,
          `Candidates Processed: ${dailyStats.candidates}`,
          `Other Actions: ${dailyStats.system}`,
          `-------------------------------------------`,
          `DETAILED LOG`,
          `Time\t\tUser\t\tAction\t\tDetails`
      ];

      dailyLogs.forEach(log => {
          const time = new Date(log.timestamp).toLocaleTimeString();
          lines.push(`${time}\t${log.userName}\t${log.action}\t${log.details}`);
      });

      const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Daily_Report_${selectedDate}.txt`;
      a.click();
      URL.revokeObjectURL(url);
  };

  // --- Monthly Report Logic ---
  const generateMonthlyData = (): MonthlyData[] => {
      const monthsMap: Record<string, MonthlyData> = {};
      
      commissions.forEach(comm => {
          const date = new Date(comm.date);
          const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
          const label = date.toLocaleString('default', { month: 'long', year: 'numeric' });
          
          if(!monthsMap[key]) {
              monthsMap[key] = {
                  id: key,
                  label: label,
                  totalRevenue: 0,
                  totalPlacements: 0,
                  activeJobsCount: 0,
                  topRecruiterId: '',
                  topRecruiterName: ''
              };
          }
          monthsMap[key].totalRevenue += comm.placementValue; 
      });

      jobs.forEach(job => {
          if(job.status === 'Closed' && job.lastActionDate) {
              const date = new Date(job.lastActionDate);
              const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}`;
              const label = date.toLocaleString('default', { month: 'long', year: 'numeric' });

              if(!monthsMap[key]) {
                  monthsMap[key] = { id: key, label: label, totalRevenue: 0, totalPlacements: 0, activeJobsCount: 0, topRecruiterId: '', topRecruiterName: '' };
              }
              monthsMap[key].totalPlacements += 1;
          }
      });

      Object.keys(monthsMap).forEach(key => {
          const monthComms = commissions.filter(c => {
             const d = new Date(c.date);
             return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}` === key;
          });
          
          const recruiterTally: Record<string, number> = {};
          monthComms.forEach(c => {
              recruiterTally[c.recipientId] = (recruiterTally[c.recipientId] || 0) + c.placementValue;
          });

          let topId = '';
          let maxVal = 0;
          Object.entries(recruiterTally).forEach(([id, val]) => {
              if(val > maxVal) { maxVal = val; topId = id; }
          });
          monthsMap[key].topRecruiterId = topId;
          monthsMap[key].topRecruiterName = users.find(u => u.id === topId)?.name || 'N/A';
      });

      return Object.values(monthsMap).sort((a, b) => b.id.localeCompare(a.id));
  };

  const monthlyData = generateMonthlyData();
  const availableYears = Array.from(new Set(monthlyData.map(d => parseInt(d.id.split('-')[0])))).sort((a, b) => b - a);
  const filteredMonthlyData = monthlyData.filter(d => d.id.startsWith(`${selectedYear}-`));

  const renderDailyTab = () => (
      <div className="space-y-6 animate-fadeIn">
          {/* Daily Controls */}
          <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-100 flex flex-wrap items-center justify-between gap-4">
              <div className="flex items-center gap-4">
                  <div>
                      <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Select Date</label>
                      <div className="relative">
                          <input 
                              type="date" 
                              className="pl-10 pr-4 py-2 border border-slate-200 rounded-lg text-sm outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                              value={selectedDate}
                              onChange={(e) => setSelectedDate(e.target.value)}
                          />
                          <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16}/>
                      </div>
                  </div>
                  {isAdmin && (
                      <div>
                          <label className="block text-xs font-bold text-slate-500 uppercase mb-1">Filter User</label>
                          <select 
                              className="w-48 py-2 px-3 border border-slate-200 rounded-lg text-sm outline-none focus:ring-2 focus:ring-blue-500 bg-white"
                              value={selectedUser}
                              onChange={(e) => setSelectedUser(e.target.value)}
                          >
                              <option value="all">All Users</option>
                              {users.map(u => <option key={u.id} value={u.id}>{u.name}</option>)}
                          </select>
                      </div>
                  )}
              </div>
              <button 
                  onClick={handleDownloadDailyReport}
                  className="flex items-center gap-2 px-4 py-2 bg-slate-800 text-white rounded-lg hover:bg-black transition-colors shadow-sm text-sm font-medium"
              >
                  <Download size={16}/> Download Report
              </button>
          </div>

          {/* Daily Stats */}
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-100 flex items-center justify-between">
                  <div>
                      <p className="text-xs font-bold text-slate-500 uppercase">Total Actions</p>
                      <p className="text-2xl font-bold text-slate-800">{dailyStats.actions}</p>
                  </div>
                  <div className="bg-blue-50 p-2 rounded-lg text-blue-500"><Activity size={20}/></div>
              </div>
              <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-100 flex items-center justify-between">
                  <div>
                      <p className="text-xs font-bold text-slate-500 uppercase">Jobs Managed</p>
                      <p className="text-2xl font-bold text-orange-600">{dailyStats.jobs}</p>
                  </div>
                  <div className="bg-orange-50 p-2 rounded-lg text-orange-500"><Briefcase size={20}/></div>
              </div>
              <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-100 flex items-center justify-between">
                  <div>
                      <p className="text-xs font-bold text-slate-500 uppercase">Candidates</p>
                      <p className="text-2xl font-bold text-green-600">{dailyStats.candidates}</p>
                  </div>
                  <div className="bg-green-50 p-2 rounded-lg text-green-500"><Users size={20}/></div>
              </div>
              <div className="bg-white p-4 rounded-xl shadow-sm border border-slate-100 flex items-center justify-between">
                  <div>
                      <p className="text-xs font-bold text-slate-500 uppercase">System/Client</p>
                      <p className="text-2xl font-bold text-purple-600">{dailyStats.system}</p>
                  </div>
                  <div className="bg-purple-50 p-2 rounded-lg text-purple-500"><List size={20}/></div>
              </div>
          </div>

          {/* Timeline Feed */}
          <div className="bg-white rounded-xl shadow-sm border border-slate-100 overflow-hidden">
              <div className="p-4 border-b border-slate-100 bg-slate-50/50">
                  <h3 className="font-bold text-slate-800 text-sm flex items-center gap-2">
                      <Clock size={16} className="text-slate-500"/> Activity Timeline - {new Date(selectedDate).toLocaleDateString()}
                  </h3>
              </div>
              <div className="divide-y divide-slate-50">
                  {dailyLogs.length > 0 ? dailyLogs.map(log => (
                      <div key={log.id} className="p-4 hover:bg-slate-50 transition-colors flex items-start gap-4">
                          <div className="w-12 text-xs text-slate-400 font-mono pt-1 text-right">
                              {new Date(log.timestamp).toLocaleTimeString([], {hour:'2-digit', minute:'2-digit'})}
                          </div>
                          <div className="relative">
                              <div className="absolute top-2 left-[-21px] w-2 h-2 rounded-full bg-slate-300 border-2 border-white"></div>
                              <img src={log.userAvatar} className="w-8 h-8 rounded-full border border-slate-200" alt=""/>
                          </div>
                          <div className="flex-1">
                              <div className="flex items-center gap-2">
                                  <span className="font-bold text-sm text-slate-800">{log.userName}</span>
                                  <span className={`text-[10px] px-1.5 py-0.5 rounded ${
                                      log.type === 'Job' ? 'bg-orange-100 text-orange-700' : 
                                      log.type === 'Candidate' ? 'bg-green-100 text-green-700' : 
                                      'bg-blue-100 text-blue-700'
                                  }`}>{log.action}</span>
                              </div>
                              <p className="text-sm text-slate-600 mt-0.5">{log.details}</p>
                          </div>
                      </div>
                  )) : (
                      <div className="p-12 text-center text-slate-400 italic">
                          No activity recorded for this date.
                      </div>
                  )}
              </div>
          </div>
      </div>
  );

  const renderMonthlyOverview = () => (
      <div className="bg-white rounded-xl shadow-sm border border-slate-100 overflow-hidden animate-fadeIn">
          <div className="p-6 border-b border-slate-100 bg-slate-50/50 flex justify-between items-center">
              <h3 className="font-bold text-slate-800">Monthly Performance Report</h3>
              <div className="flex items-center gap-3">
                  <div className="relative">
                      <select 
                          value={selectedYear}
                          onChange={(e) => setSelectedYear(Number(e.target.value))}
                          className="pl-3 pr-8 py-1.5 bg-white border border-slate-200 rounded-lg text-sm font-medium outline-none focus:ring-2 focus:ring-slate-200 appearance-none cursor-pointer"
                      >
                          {availableYears.map(y => <option key={y} value={y}>{y}</option>)}
                          {!availableYears.includes(new Date().getFullYear()) && <option value={new Date().getFullYear()}>{new Date().getFullYear()}</option>}
                      </select>
                      <ChevronDown size={14} className="absolute right-2.5 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none"/>
                  </div>
              </div>
          </div>
          <div className="overflow-x-auto">
              <table className="w-full text-left text-sm text-slate-600">
                  <thead className="bg-slate-50 text-xs uppercase font-medium text-slate-500">
                      <tr>
                          <th className="px-6 py-4">Month</th>
                          <th className="px-6 py-4 text-right">Total Revenue</th>
                          <th className="px-6 py-4 text-center">Placements</th>
                          <th className="px-6 py-4">Top Performer</th>
                      </tr>
                  </thead>
                  <tbody className="divide-y divide-slate-100">
                      {filteredMonthlyData.length > 0 ? filteredMonthlyData.map(data => (
                          <tr key={data.id} className="hover:bg-slate-50 transition-colors">
                              <td className="px-6 py-4 font-medium text-slate-800 flex items-center gap-2">
                                  <Calendar size={16} className="text-slate-400"/> {data.label}
                              </td>
                              <td className="px-6 py-4 text-right font-mono text-green-700 font-bold">
                                  R {data.totalRevenue.toLocaleString()}
                              </td>
                              <td className="px-6 py-4 text-center">
                                  <span className="inline-block px-3 py-1 bg-blue-50 text-blue-700 rounded-full font-medium text-xs">
                                      {data.totalPlacements} Placements
                                  </span>
                              </td>
                              <td className="px-6 py-4">
                                  {data.topRecruiterName !== 'N/A' ? (
                                      <div className="flex items-center gap-2">
                                          <div className="w-6 h-6 rounded-full bg-amber-100 text-amber-700 flex items-center justify-center text-xs font-bold">
                                              {data.topRecruiterName.charAt(0)}
                                          </div>
                                          <span>{data.topRecruiterName}</span>
                                      </div>
                                  ) : (
                                      <span className="text-slate-400 italic">No Data</span>
                                  )}
                              </td>
                          </tr>
                      )) : (
                          <tr>
                              <td colSpan={4} className="p-12 text-center text-slate-400">
                                  <Calendar size={48} className="mx-auto mb-3 opacity-20"/>
                                  <p>No report data available for {selectedYear}.</p>
                              </td>
                          </tr>
                      )}
                  </tbody>
              </table>
          </div>
      </div>
  );

  return (
    <div className="max-w-6xl mx-auto pb-20">
        <div className="mb-8">
             <h2 className="text-2xl font-bold text-slate-800">Reports & Activity Portal</h2>
             <p className="text-slate-500 mt-1">Daily logs, operational pulse, and monthly performance archives.</p>
        </div>

        <div className="flex items-center gap-1 bg-slate-100 p-1 rounded-lg mb-6 w-fit">
            <button 
                onClick={() => setActiveTab('daily')}
                className={`px-4 py-2 rounded-md text-sm font-medium transition-all ${activeTab === 'daily' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
            >
                Daily Activity Log
            </button>
            {isAdmin && (
                <button 
                    onClick={() => setActiveTab('monthly')}
                    className={`px-4 py-2 rounded-md text-sm font-medium transition-all ${activeTab === 'monthly' ? 'bg-white text-slate-800 shadow-sm' : 'text-slate-500 hover:text-slate-700'}`}
                >
                    Monthly Overview
                </button>
            )}
        </div>

        {activeTab === 'daily' && renderDailyTab()}
        {activeTab === 'monthly' && renderMonthlyOverview()}
    </div>
  );
};

export default MonthlyReports;
